export const HAZARDS=["earthquake","typhoon","heavyRain","powerOutage","waterOutage"];
export const HAZARD_LABELS={earthquake:"地震",typhoon:"台風",heavyRain:"豪雨",powerOutage:"停電",waterOutage:"断水"};
export const CATEGORIES=["water","food","medical","light","hygiene","documents","other"];
export function dateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return`${y}-${m}-${d}`}
export const PROCEDURES=[
  {id:"eq-drop",hazard:"earthquake",phase:"now",title:"頭を守り、揺れが収まるまで待つ",body:"机の下など安全な場所で頭を守ります。あわてて外へ飛び出さないでください。",keywords:["机","頭","揺れ"]},
  {id:"eq-fire",hazard:"earthquake",phase:"after",title:"火元と出口を確認する",body:"揺れが収まってから火元を確認し、靴を履いて出口を確保します。",keywords:["火","出口","靴"]},
  {id:"eq-evacuate",hazard:"earthquake",phase:"after",title:"危険なら安全な場所へ移動する",body:"建物の損傷や火災の危険がある場合は、登録した集合場所へ移動します。公的な避難情報を優先してください。",keywords:["避難","集合"]},
  {id:"ty-secure",hazard:"typhoon",phase:"prepare",title:"窓から離れ、飛びやすい物を片付ける",body:"風が強くなる前に屋外の物を固定し、雨戸やカーテンを閉めます。",keywords:["窓","風","片付け"]},
  {id:"ty-charge",hazard:"typhoon",phase:"prepare",title:"充電と持ち出し品を確認する",body:"スマートフォンと予備電源を充電し、持ち出し品を玄関近くへ置きます。",keywords:["充電","持ち出し"]},
  {id:"ty-stay",hazard:"typhoon",phase:"now",title:"外へ出ず、窓から離れる",body:"暴風中は屋内の窓から離れた場所で過ごし、公的な情報を確認します。",keywords:["屋内","窓"]},
  {id:"rain-upper",hazard:"heavyRain",phase:"now",title:"低い場所から離れる",body:"地下・川沿い・崖の近くを避け、危険が迫る前に高い場所へ移動します。",keywords:["川","崖","高い場所"]},
  {id:"rain-early",hazard:"heavyRain",phase:"prepare",title:"明るいうちに早めの避難を判断する",body:"高齢者や子どもがいる場合は特に早めに移動します。公的な避難情報を優先してください。",keywords:["早め","避難"]},
  {id:"rain-no-car",hazard:"heavyRain",phase:"now",title:"浸水した道へ入らない",body:"冠水した道路は深さが分かりません。徒歩でも車でも進入しないでください。",keywords:["浸水","道路","車"]},
  {id:"power-light",hazard:"powerOutage",phase:"now",title:"懐中電灯を用意する",body:"転倒防止のため、ろうそくより懐中電灯を使います。",keywords:["ライト","暗い"]},
  {id:"power-plug",hazard:"powerOutage",phase:"after",title:"電熱器具のプラグを抜く",body:"通電火災を防ぐため、アイロンやヒーターなどのプラグを抜きます。",keywords:["プラグ","火災"]},
  {id:"power-battery",hazard:"powerOutage",phase:"after",title:"電池を節約する",body:"画面を暗くし、不要な通信を控え、連絡手段の電池を残します。",keywords:["電池","スマホ"]},
  {id:"water-store",hazard:"waterOutage",phase:"prepare",title:"清潔な容器に水を確保する",body:"断水前に予告がある場合は、飲料用と生活用を分けて確保します。",keywords:["水","容器"]},
  {id:"water-valve",hazard:"waterOutage",phase:"now",title:"復旧情報を確認し、蛇口を閉める",body:"蛇口を閉め、復旧時の出しっぱなしを防ぎます。外部情報は別手段で確認してください。",keywords:["蛇口","復旧"]},
  {id:"water-hygiene",hazard:"waterOutage",phase:"after",title:"飲料水を優先して使う",body:"飲める水を先に確保し、衛生用品や簡易トイレを活用します。",keywords:["飲料","衛生","トイレ"]}
];
const isText=(v,max)=>typeof v==="string"&&v.trim().length>0&&v.trim().length<=max;
const validDate=v=>{if(v===null)return true;if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const[y,m,d]=v.split("-").map(Number),date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d};
export function uid(now=Date.now()){return`${now}-${Math.random().toString(36).slice(2,9)}`}
export function defaultState(){return{schemaVersion:1,mode:"normal",selectedHazard:null,emergencyCheckedIds:[],supplies:[],locations:[],familyMembers:[],favoriteProcedureIds:[],insurance:{status:"unknown",coverages:{earthquake:false,stormFlood:false,household:false},policyLocation:"",renewalOn:null,lastCheckedOn:null,note:""},ui:{view:"home",supplyTab:"goBag",search:"",hazardFilter:"all"}}}
export function validateSupply(input,locationIds=[]){const errors={};const name=String(input.name??"").trim(),quantity=Number(input.quantity),minimumQuantity=Number(input.minimumQuantity),unit=String(input.unit??"").trim(),note=String(input.note??"").trim(),expiresOn=input.expiresOn||null,locationId=input.locationId||null;if(!name)errors.name="品名を入力してください。";else if(name.length>40)errors.name="品名は40文字以内で入力してください。";if(!Number.isInteger(quantity)||quantity<0||quantity>9999)errors.quantity="数量は0〜9999の整数で入力してください。";if(!Number.isInteger(minimumQuantity)||minimumQuantity<0||minimumQuantity>9999)errors.minimumQuantity="必要数は0〜9999の整数で入力してください。";if(!unit||unit.length>12)errors.unit="単位は1〜12文字で入力してください。";if(!validDate(expiresOn))errors.expiresOn="実在する日付を入力してください。";if(locationId&&!locationIds.includes(locationId))errors.locationId="登録済みの保管場所を選んでください。";if(note.length>300)errors.note="メモは300文字以内で入力してください。";return{valid:!Object.keys(errors).length,errors,value:{name,category:CATEGORIES.includes(input.category)?input.category:"other",quantity,minimumQuantity,unit,expiresOn,locationId,isGoBag:Boolean(input.isGoBag),isReady:Boolean(input.isReady),note}}}
export function validateLocation(input){const name=String(input.name??"").trim(),note=String(input.note??"").trim(),errors={};if(!name)errors.name="場所名を入力してください。";else if(name.length>30)errors.name="場所名は30文字以内で入力してください。";if(note.length>200)errors.note="メモは200文字以内で入力してください。";return{valid:!Object.keys(errors).length,errors,value:{name,note}}}
export function validateFamily(input){const label=String(input.label??"").trim(),contactNote=String(input.contactNote??"").trim(),meetingPlace=String(input.meetingPlace??"").trim(),considerations=String(input.considerations??"").trim(),errors={};if(!label)errors.label="呼び名を入力してください。";else if(label.length>30)errors.label="呼び名は30文字以内で入力してください。";for(const[k,v]of Object.entries({contactNote,meetingPlace,considerations}))if(v.length>300)errors[k]="300文字以内で入力してください。";return{valid:!Object.keys(errors).length,errors,value:{label,contactNote,meetingPlace,considerations}}}
export function validateInsurance(input){const errors={},status=["unknown","none","insured"].includes(input.status)?input.status:"unknown",policyLocation=String(input.policyLocation??"").trim(),note=String(input.note??"").trim(),renewalOn=input.renewalOn||null,lastCheckedOn=input.lastCheckedOn||null;if(policyLocation.length>100)errors.policyLocation="保管場所は100文字以内で入力してください。";if(note.length>300)errors.note="メモは300文字以内で入力してください。";if(!validDate(renewalOn))errors.renewalOn="実在する日付を入力してください。";if(!validDate(lastCheckedOn))errors.lastCheckedOn="実在する日付を入力してください。";return{valid:!Object.keys(errors).length,errors,value:{status,coverages:{earthquake:Boolean(input.coverages?.earthquake),stormFlood:Boolean(input.coverages?.stormFlood),household:Boolean(input.coverages?.household)},policyLocation,renewalOn,lastCheckedOn,note}}}
export function searchProcedures(query="",hazard="all",favorites=[],onlyFavorites=false){const q=String(query).trim().toLowerCase();return PROCEDURES.filter(p=>(hazard==="all"||p.hazard===hazard)&&(!onlyFavorites||favorites.includes(p.id))&&(!q||[p.title,p.body,...p.keywords].join(" ").toLowerCase().includes(q)))}
export function toggleFavorite(ids,id){if(!PROCEDURES.some(p=>p.id===id))return ids;return ids.includes(id)?ids.filter(x=>x!==id):[...new Set([...ids,id])]}
export function preparedness(state,today=new Date()){const supplies=state.supplies,go=supplies.filter(x=>x.isGoBag),ready=go.filter(x=>x.isReady&&x.quantity>=x.minimumQuantity).length,family=state.familyMembers.length>0,meeting=state.familyMembers.some(x=>x.meetingPlace),insurance=state.insurance.lastCheckedOn!==null,total=3+go.length,done=(family?1:0)+(meeting?1:0)+(insurance?1:0)+ready,day=dateKey(today),expiring=supplies.filter(x=>x.expiresOn&&x.expiresOn<=day),short=supplies.filter(x=>x.quantity<x.minimumQuantity);return{done,total,percent:total?Math.round(done/total*100):0,expiring,short,goBagReady:ready,goBagTotal:go.length}}
export function insuranceSuggestions(insurance,today=new Date()){const out=[];if(insurance.status==="unknown")out.push("加入状況を確認しましょう。");if(insurance.status==="none")out.push("災害時に使える公的支援と、必要な備えを確認しましょう。");if(insurance.status==="insured"){if(!insurance.coverages.earthquake)out.push("地震による損害が確認対象か、契約内容を見直しましょう。");if(!insurance.coverages.stormFlood)out.push("風災・水災が確認対象か、契約内容を見直しましょう。");if(!insurance.coverages.household)out.push("家財が確認対象か、契約内容を見直しましょう。")}const day=86400000;if(!insurance.lastCheckedOn||today-new Date(`${insurance.lastCheckedOn}T00:00:00`)>365*day)out.push("前回確認から1年以上です。契約内容と連絡先を確認しましょう。");if(insurance.renewalOn){const diff=(new Date(`${insurance.renewalOn}T00:00:00`)-today)/day;if(diff>=0&&diff<=30)out.push("更新日まで30日以内です。変更点を確認しましょう。");}return out.length?out:["現在、急いで確認する項目はありません。次回確認日を決めておきましょう。"]}
export function startEmergency(state,hazard){if(!HAZARDS.includes(hazard))return{state,changed:false};return{state:{...state,mode:"emergency",selectedHazard:hazard,emergencyCheckedIds:[],ui:{...state.ui,view:"emergency"}},changed:true}}
export function toggleEmergencyCheck(state,id){if(!PROCEDURES.some(p=>p.id===id&&p.hazard===state.selectedHazard))return state;const ids=state.emergencyCheckedIds.includes(id)?state.emergencyCheckedIds.filter(x=>x!==id):[...state.emergencyCheckedIds,id];return{...state,emergencyCheckedIds:ids}}
export function safeState(raw){const base=defaultState();if(!raw||raw.schemaVersion!==1)return base;const locations=Array.isArray(raw.locations)?raw.locations.filter(x=>x&&typeof x.id==="string"&&isText(x.name,30)).map(x=>({id:x.id,name:x.name.trim(),note:typeof x.note==="string"?x.note.slice(0,200):""})).slice(-30):[];const locationIds=locations.map(x=>x.id);const supplies=Array.isArray(raw.supplies)?raw.supplies.filter(x=>x&&typeof x.id==="string").flatMap(x=>{const v=validateSupply(x,locationIds);return v.valid?[{...v.value,id:x.id,createdAt:Number.isFinite(x.createdAt)?x.createdAt:0,updatedAt:Number.isFinite(x.updatedAt)?x.updatedAt:0}]:[]}).slice(-200):[];const familyMembers=Array.isArray(raw.familyMembers)?raw.familyMembers.filter(x=>x&&typeof x.id==="string").flatMap(x=>{const v=validateFamily(x);return v.valid?[{...v.value,id:x.id}]:[]}).slice(-20):[];const iv=validateInsurance(raw.insurance??base.insurance);const favorites=Array.isArray(raw.favoriteProcedureIds)?[...new Set(raw.favoriteProcedureIds.filter(id=>PROCEDURES.some(p=>p.id===id)))]:[];const hazard=HAZARDS.includes(raw.selectedHazard)?raw.selectedHazard:null,mode=raw.mode==="emergency"&&hazard?"emergency":"normal",checked=Array.isArray(raw.emergencyCheckedIds)?[...new Set(raw.emergencyCheckedIds.filter(id=>PROCEDURES.some(p=>p.id===id&&p.hazard===hazard)))]:[];return{...base,mode,selectedHazard:hazard,emergencyCheckedIds:checked,supplies,locations,familyMembers,favoriteProcedureIds:favorites,insurance:iv.valid?iv.value:base.insurance,ui:{view:["home","supplies","procedures","family","emergency"].includes(raw.ui?.view)?raw.ui.view:"home",supplyTab:["goBag","stock","locations","insurance"].includes(raw.ui?.supplyTab)?raw.ui.supplyTab:"goBag",search:typeof raw.ui?.search==="string"?raw.ui.search.slice(0,50):"",hazardFilter:["all",...HAZARDS].includes(raw.ui?.hazardFilter)?raw.ui.hazardFilter:"all"}}}
